[web]
13.217.24.63 ansible_user=ec2-user ansible_ssh_private_key_file=/mnt/c/ecommerce-devops-lab/devops-key.pem ansible_python_interpreter=/usr/local/bin/python3.9

[local]
localhost ansible_connection=local ansible_python_interpreter=/home/hajer/ansible-env/bin/python3

[all:children]
web
local
