[web]
3.86.197.102 ansible_user=ubuntu ansible_ssh_private_key_file=key.pem
54.175.37.185 ansible_user=ubuntu ansible_ssh_private_key_file=key.pem

[web:vars]
ansible_python_interpreter=/usr/bin/python3
